version: '3.8'

services:
  db:
    image: postgres:15
    container_name: itunes_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itunes_podcast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
